# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - eslint
repos:
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
          - --exclude-files
          - README.md
          - --exclude-files
          - .yarn/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, scss, sass, css, yaml, markdown]
        args:
          - --no-config
          - --no-semi
        exclude: "(node_modules/|.yarn/)"
