name: CI
on: [push]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    env:
      SKIP_YARN_COREPACK_CHECK: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20.19.0
          cache: "yarn"

      - run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
