name: CI
on: [push]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    env:
      SKIP_YARN_COREPACK_CHECK: true
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 20.8.1
          cache: "yarn"

      - run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
